language: php

php:
  - 5.6

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - ls -l
  - mysql -u root -e 'CREATE DATABASE obrok_is_tests CHARACTER SET utf8 COLLATE utf8_general_ci;';
  - php www/index.php orm:schema-tool:create
  #  - mysql -u root testbase < tests/testbase.sql

script:
  - ./vendor/bin/tester -s ./tests/

after_failure:
  # Vytiskne obsah souborù *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
