language: php

php:
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - ls -l
  # - mysql -u root -e 'CREATE DATABASE obrok_is_tests CHARACTER SET utf8 COLLATE utf8_general_ci;';
  # - mysql -u root testbase < tests/testbase.sql

script:
  # - ./vendor/bin/tester -s ./tests/ -C

after_failure:
  - cat log/error.log
  - cat log/exception.log
